version: "3.8"
services:
    api:
      container_name: biscuit-machine-api
      build:
        context: .
        dockerfile: server/Web/TheBiscuitMachine.Web/Dockerfile
      ports:
        - "8080:80"
      depends_on:
        - db
    ui:
      container_name: biscuit-machine-ui
      build:
        context: .
        dockerfile: ui/Dockerfile
      ports:
        - "5000:80"
      depends_on:
        - api
    db:
      container_name: biscuit-machine-db
      image: "mcr.microsoft.com/mssql/server:2019-latest"
      ports:
        - "1433:1433"
      environment:
        SA_PASSWORD: "Strongpassword1!"
        ACCEPT_EULA: "Y"    